[project]
name = "threshold-handle"
authors = ["Decentralized Access Control Team"]
description = "A decentralized access control platform using threshold cryptography"
telemetry = false
requirements = []

[contracts.identity-registry]
path = "contracts/identity-registry.clar"
depends_on = []

[contracts.permission-arbiter]
path = "contracts/permission-arbiter.clar"
depends_on = []

[contracts.challenge-mechanism]
path = "contracts/challenge-mechanism.clar"
depends_on = []

[contracts.delegation-protocol]
path = "contracts/delegation-protocol.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
